version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1  # Enable Django debug mode in development

  web-prod:
    build: .
    command: gunicorn -c conf/gunicorn_config.py django_staff.wsgi
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      DEBUG: 0  # Disable Django debug mode in production

volumes:
  static_volume:
  media_volume:
