# Generated by Django 4.2.11 on 2024-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_record', '0002_overtimerecord_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
