# Generated by Django 4.2.11 on 2024-04-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_record', '0003_overtimerecord_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerecord',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
