# Generated by Django 4.2.11 on 2024-03-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
