# Generated by Django 4.2.11 on 2024-03-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departments',
            new_name='department',
        ),
    ]
